import { StyleSheet, Platform } from 'react-native';

export const colors = {
  bg: '#0B0F19',
  bgCard: '#161D30',
  bgInput: '#0B0F19',
  border: '#1F2937',
  textPrimary: '#F9FAFB',
  textSecondary: '#9CA3AF',
  textMuted: '#6B7280',
  accent: '#3B82F6',
  success: '#10B981',
  danger: '#EF4444',
  warning: '#F59E0B',
  codeBg: '#05070F',
  codeText: '#10B981',
};

const mono = Platform.OS === 'ios' ? 'Courier' : 'monospace';

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  modeTabs: { flexDirection: 'row', backgroundColor: colors.bgCard, borderRadius: 8, padding: 4, marginBottom: 20, borderWidth: 1, borderColor: colors.border },
  modeTabButton: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 6 },
  modeTabActive: { backgroundColor: '#1E293B', borderColor: colors.accent },
  modeTabText: { color: colors.textSecondary, fontSize: 13, fontWeight: 'bold' },
  modeTabActiveText: { color: colors.accent },
  scrollContainer: { padding: 20, justifyContent: 'center', minHeight: '100%' },
  card: { backgroundColor: colors.bgCard, borderRadius: 16, padding: 24, borderWidth: 1, borderColor: colors.border, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 5 },
  appTitle: { fontSize: 26, fontWeight: 'bold', color: colors.textPrimary, textAlign: 'center', marginBottom: 8 },
  subtitle: { fontSize: 14, color: colors.textSecondary, textAlign: 'center', marginBottom: 28, lineHeight: 20 },
  inputGroup: { marginBottom: 20 },
  inputLabel: { fontSize: 12, fontWeight: '600', color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 8 },
  input: { backgroundColor: colors.bgInput, borderRadius: 8, color: colors.textPrimary, paddingHorizontal: 16, paddingVertical: 12, fontSize: 15, borderWidth: 1, borderColor: colors.border },
  primaryButton: { backgroundColor: colors.success, borderRadius: 8, paddingVertical: 14, alignItems: 'center', marginTop: 10 },
  buttonText: { color: '#0F172A', fontWeight: 'bold', fontSize: 15 },
  infoCard: { backgroundColor: '#111827', borderRadius: 12, padding: 16, marginTop: 20, borderWidth: 1, borderColor: colors.border },
  infoTitle: { fontSize: 14, fontWeight: 'bold', color: colors.textPrimary, marginBottom: 10 },
  infoText: { fontSize: 12, color: colors.textSecondary, lineHeight: 18, marginBottom: 6 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 16, borderBottomWidth: 1, borderColor: colors.border, backgroundColor: colors.bgCard },
  headerTitle: { fontSize: 18, fontWeight: 'bold', color: colors.textPrimary },
  headerSubtitle: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
  headerActions: { flexDirection: 'row', alignItems: 'center' },
  headerActionButton: { padding: 8, marginRight: 10 },
  pushActionButton: { backgroundColor: colors.accent, borderRadius: 6, paddingHorizontal: 12, paddingVertical: 8 },
  pushActionButtonText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 13 },
  outlineButton: { borderColor: colors.accent, borderWidth: 1, borderRadius: 8, paddingHorizontal: 16, paddingVertical: 10 },
  outlineButtonDanger: { borderColor: colors.danger, borderWidth: 1, borderRadius: 6, paddingHorizontal: 10, paddingVertical: 6 },
  buttonTextDanger: { color: colors.danger, fontSize: 12, fontWeight: '600' },
  listContainer: { padding: 16 },
  workspaceItem: { backgroundColor: colors.bgCard, borderRadius: 12, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: colors.border },
  workspaceRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  workspaceName: { fontSize: 16, fontWeight: 'bold', color: colors.textPrimary },
  workspacePath: { fontSize: 11, color: colors.textMuted, marginTop: 4 },
  badgeContainer: { alignItems: 'flex-end' },
  branchText: { fontSize: 12, color: colors.textSecondary, fontWeight: '500' },
  dangerBadge: { backgroundColor: 'rgba(239, 68, 68, 0.15)', borderRadius: 4, paddingHorizontal: 6, paddingVertical: 2, marginTop: 6 },
  dangerBadgeText: { color: colors.danger, fontSize: 10, fontWeight: 'bold' },
  successBadge: { backgroundColor: 'rgba(16, 185, 129, 0.15)', borderRadius: 4, paddingHorizontal: 6, paddingVertical: 2, marginTop: 6 },
  successBadgeText: { color: colors.success, fontSize: 10, fontWeight: 'bold' },
  emptyContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 80 },
  emptyText: { color: colors.textSecondary, fontSize: 14, textAlign: 'center', marginBottom: 20 },
  bottomBar: { backgroundColor: colors.bgCard, borderTopWidth: 1, borderColor: colors.border, padding: 16 },
  fullWidthButton: { backgroundColor: colors.accent, borderRadius: 8, paddingVertical: 14, alignItems: 'center' },
  backButton: { paddingVertical: 8 },
  backButtonText: { color: colors.accent, fontWeight: 'bold', fontSize: 15 },
  disabledBtn: { backgroundColor: colors.border, opacity: 0.5 },
  section: { marginBottom: 24 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12, borderBottomWidth: 1, borderColor: colors.border, paddingBottom: 6 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', color: colors.textSecondary, textTransform: 'uppercase' },
  sectionLink: { color: colors.accent, fontSize: 12, fontWeight: '600' },
  fileRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.bgCard, borderRadius: 8, paddingHorizontal: 12, marginBottom: 8, borderWidth: 1, borderColor: colors.border },
  fileCheckbox: { marginRight: 12 },
  checkedBox: { color: colors.success, fontSize: 16, fontWeight: 'bold' },
  uncheckedBox: { color: '#4B5563', fontSize: 16 },
  filePathText: { color: colors.textPrimary, fontSize: 14, fontWeight: '500' },
  fileStatusText: { fontSize: 11, marginTop: 2, textTransform: 'capitalize' },
  diffBadge: { backgroundColor: colors.border, borderRadius: 4, paddingHorizontal: 10, paddingVertical: 6 },
  diffBadgeText: { color: colors.accent, fontSize: 12, fontWeight: '600' },
  commitBox: { backgroundColor: colors.bgCard, borderTopWidth: 1, borderColor: colors.border, padding: 16 },
  commitInput: { backgroundColor: colors.bgInput, borderRadius: 8, color: colors.textPrimary, padding: 12, fontSize: 14, borderWidth: 1, borderColor: colors.border, minHeight: 60, textAlignVertical: 'top', marginBottom: 12 },
  commitButton: { backgroundColor: colors.success, borderRadius: 8, paddingVertical: 12, alignItems: 'center' },
  commitButtonText: { color: '#0F172A', fontWeight: 'bold', fontSize: 14 },
  codeEditor: { flex: 1, backgroundColor: colors.codeBg, color: colors.codeText, fontFamily: mono, fontSize: 13, padding: 16, textAlignVertical: 'top' },
  diffContainer: { flex: 1, backgroundColor: colors.bg },
  diffHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, borderColor: colors.border, backgroundColor: colors.bgCard },
  diffHeaderTitle: { fontSize: 15, fontWeight: 'bold', color: colors.textPrimary },
  diffHeaderSubtitle: { fontSize: 11, color: colors.textSecondary, marginTop: 2 },
  stageToggleBtn: { backgroundColor: colors.success, borderRadius: 4, paddingHorizontal: 12, paddingVertical: 6 },
  stageToggleBtnText: { color: '#0F172A', fontSize: 12, fontWeight: 'bold' },
  diffScroll: { flex: 1 },
  diffCodeWrapper: { paddingVertical: 12 },
  diffLineContainer: { flexDirection: 'row', paddingRight: 20, paddingVertical: 1 },
  lineNumber: { width: 35, textAlign: 'right', fontSize: 10, color: '#4B5563', fontFamily: mono, marginRight: 10, userSelect: 'none' },
  diffTextNormal: { color: '#E5E7EB', fontSize: 12, fontFamily: mono },
  diffTextAdd: { color: colors.success, fontSize: 12, fontFamily: mono },
  diffTextDelete: { color: colors.danger, fontSize: 12, fontFamily: mono },
  diffTextHeader: { color: '#60A5FA', fontSize: 12, fontWeight: 'bold', fontFamily: mono },
  diffTextMeta: { color: colors.textSecondary, fontSize: 12, fontFamily: mono },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalCard: { backgroundColor: colors.bgCard, borderRadius: 12, width: '100%', maxHeight: '80%', borderWidth: 1, borderColor: colors.border, padding: 16 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderColor: colors.border, paddingBottom: 10, marginBottom: 12 },
  modalTitle: { color: colors.textPrimary, fontSize: 16, fontWeight: 'bold' },
  modalCloseText: { color: colors.accent, fontWeight: 'bold' },
  consoleBody: { backgroundColor: colors.bg, borderRadius: 8, padding: 12, borderWidth: 1, borderColor: colors.border },
  consoleText: { color: colors.codeText, fontFamily: mono, fontSize: 12, lineHeight: 18 },
  globalLoader: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(11, 15, 25, 0.7)', alignItems: 'center', justifyContent: 'center' },
  searchBar: { backgroundColor: colors.bgInput, borderRadius: 8, color: colors.textPrimary, paddingHorizontal: 16, paddingVertical: 10, fontSize: 14, borderWidth: 1, borderColor: colors.border, marginBottom: 12 },
});
